# This file was generated by GoReleaser. DO NOT EDIT.
cask "auto" do
  version "0.50.85"

  on_macos do
    on_intel do
      sha256 "66834d509309cb09b84f78bb81a97e68a8d03434c9a37f239a2ae04677dbc10b"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7fe10bc7b03b3df44f803622e3830e5e91f3ea12b47b706cf14f716b076b012e"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "187620011ce035f6bdb09f3f6d5b005f878463c3ba0fd805142cbd3e4f587698"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "654e42612a3f1ee670157cd461b3dff1270f2102b085984951975c0284356172"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "auto"
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "auto"

  # No zap stanza required

end
