# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auto < Formula
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"
  version "0.50.65"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.65/autopus-adk_0.50.65_darwin_amd64.tar.gz"
      sha256 "7f9c6b3085c8bd77a77cab700702334f0d6df5146b8098b99eb612360c25b691"

      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.65/autopus-adk_0.50.65_darwin_arm64.tar.gz"
      sha256 "5bc19cbc44a0e20f0a55fedf017a1d8704c28355e33961124e52ac0796f47787"

      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.65/autopus-adk_0.50.65_linux_amd64.tar.gz"
      sha256 "969f30f1a20bc0ab3e68eda317bf8bb5d20d5ce87213cb3fb9a3e7b6cac797a9"
      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.65/autopus-adk_0.50.65_linux_arm64.tar.gz"
      sha256 "4039460f28eac6ddbb778351a7daa7b31f84a78991daa1c53b2cbdac2aae356c"
      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  test do
    system "#{bin}/auto", "version"
  end
end
