# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auto < Formula
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"
  version "0.50.62"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.62/autopus-adk_0.50.62_darwin_amd64.tar.gz"
      sha256 "7605c64c9fea5cf8d47f666a24c90119e2c37f83f88c5c571a5697bfd47b7aa8"

      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.62/autopus-adk_0.50.62_darwin_arm64.tar.gz"
      sha256 "be6b9ccb1d7cc79072815340f3bd4e13277db088ec31cd5c352bc80f71806291"

      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.62/autopus-adk_0.50.62_linux_amd64.tar.gz"
      sha256 "d0cf88e0b9b5ccbe5f6a9344719d350bff219838447ed9390925cda3317769b8"
      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.62/autopus-adk_0.50.62_linux_arm64.tar.gz"
      sha256 "a8aac4055c20909f7ac18936ed41d9f596fbed64527a133348075aa47fff874b"
      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  test do
    system "#{bin}/auto", "version"
  end
end
