# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auto < Formula
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"
  version "0.50.61"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.61/autopus-adk_0.50.61_darwin_amd64.tar.gz"
      sha256 "30cf98fcfa37ff90288863e04851a84f4114fcf91986be59b299380def50dbf4"

      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.61/autopus-adk_0.50.61_darwin_arm64.tar.gz"
      sha256 "4e3bfbbbf26ceba3a43efc7c4cc64c9095a6aa096842b3f1ed0f17db2da7f7ca"

      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.61/autopus-adk_0.50.61_linux_amd64.tar.gz"
      sha256 "a458145b4a88e32f7be1b45d0a4537fb75e392054f11927f63f8b060e9933d1c"
      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/v0.50.61/autopus-adk_0.50.61_linux_arm64.tar.gz"
      sha256 "a88362fbbaf72459bfdafc7f6a1222566f93c1829c9a04abd2bd9e31d7eed410"
      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  test do
    system "#{bin}/auto", "version"
  end
end
